#!/usr/bin/bash

# Put User Themes in the system list of enabled extensions.
#
# float-theme-sync also enables it, but it runs after the session starts, and
# gnome-shell has already read its extension list by then. An extension enabled
# mid session is not loaded until the shell restarts, which means the shell
# theme only showed up on the second login. Writing the key into the system
# database instead gets it read at shell startup, so it works on the first one.
#
# The list is merged rather than replaced. The base image enables dash-to-dock,
# appindicator and the rest through its own dconf files, and this file is named
# so it is merged last, which means whatever is written here wins for accounts
# with no value of their own. Hardcoding a list would quietly take the dock
# down, so the base list is read back and appended to instead.

set -euo pipefail

UUID=user-theme@gnome-shell-extensions.gcampari.github.com
DBDIR=/etc/dconf/db
TARGET="$DBDIR/distro.d/10-float-shell-extensions"

if [[ ! -d $DBDIR ]]; then
    echo "error: $DBDIR does not exist" >&2
    exit 1
fi

# dconf merges every *.d directory in sorted order, and inside a directory the
# files in sorted order, later winning. The same walk collects the keyfile that
# currently has the final word on this key.
mapfile -t sources < <(
    for dir in "$DBDIR"/*.d; do
        [[ -d $dir ]] || continue
        for f in "$dir"/*; do
            [[ -f $f ]] || continue
            if grep -qE '^\s*enabled-extensions\s*=' "$f" 2>/dev/null; then
                printf '%s\n' "$f"
            fi
        done
    done
)

current=""
if ((${#sources[@]})); then
    current=$(sed -nE "s/^\s*enabled-extensions\s*=\s*(.*)$/\1/p" "${sources[-1]}" | tail -1)
    echo "  base list from ${sources[-1]}"
fi

merged=$(python3 - "$UUID" "${current:-@as []}" <<'PY'
import re
import sys

uuid, raw = sys.argv[1], sys.argv[2].strip()

if raw in ("", "@as []", "'@as []'"):
    print("['%s']" % uuid)
    raise SystemExit

if not (raw.startswith("[") and raw.endswith("]")):
    sys.exit("cannot parse existing enabled-extensions: %r" % raw)

entries = re.findall(r"'((?:[^'\\]|\\.)*)'", raw)
if not entries:
    sys.exit("no entries parsed out of enabled-extensions: %r" % raw)

for e in entries:
    if e.replace("\\'", "'") == uuid:
        print(raw)          # already there, leave the base list exactly as it is
        raise SystemExit

print("[" + ", ".join("'%s'" % e for e in entries + [uuid]) + "]")
PY
)

if [[ $merged == "${current:-@as []}" ]]; then
    echo "  $UUID already in the system list"
else
    mkdir -p "$(dirname "$TARGET")"
    {
        echo "# Generated by enable-user-theme-systemwide.sh, merged from the base image list."
        echo "[org/gnome/shell]"
        echo "enabled-extensions=$merged"
    } >"$TARGET"
    echo "  wrote $TARGET"
    echo "    enabled-extensions=$merged"
fi

if command -v dconf >/dev/null 2>&1; then
    dconf update
    if dconf dump /org/gnome/shell/ 2>/dev/null | grep -q "$UUID"; then
        echo "  compiled: $UUID is in the system extension list"
    else
        echo "error: $UUID is not in the compiled dconf database" >&2
        exit 1
    fi
else
    echo "  dconf not installed, left the database uncompiled"
fi
