#!/usr/bin/bash

# Put User Themes in the system list of enabled extensions.
#
# float-theme-sync also enables it, but it runs after the session starts, and
# gnome-shell has already read its extension list by then. An extension enabled
# mid session is not loaded until the shell restarts, which is why the shell
# theme only showed up on the second login. Writing the key into the system
# database instead gets it read at shell startup, so it works on the first one.

set -euo pipefail

DBDIR=/etc/dconf/db
TARGET="$DBDIR/distro.d/10-float-shell-extensions"
EXTDIR=/usr/share/gnome-shell/extensions

# ---------------------------------------------------------------- the uuid
#
# Do not hardcode this. It was wrong once already: the name was written as
# user-theme@gnome-shell-extensions.gcampari.github.com, while the extension
# BlueBuild actually installs is gcampax. Nothing complained, the key was
# written, dconf compiled it and the shell silently never loaded anything,
# because an unknown uuid in the list is not an error.
#
# metadata.json is what the extension itself declares, so ask it.
UUID=""
for meta in "$EXTDIR"/*/metadata.json; do
    [[ -f $meta ]] || continue
    if grep -qE '"name"[[:space:]]*:[[:space:]]*"User Themes"' "$meta"; then
        UUID=$(sed -n 's/.*"uuid"[[:space:]]*:[[:space:]]*"\([^"]*\)".*/\1/p' "$meta" | head -1)
        [[ -n $UUID ]] && break
    fi
done

if [[ -z $UUID ]]; then
    echo "error: no extension declaring itself \"User Themes\" under $EXTDIR" >&2
    echo "       the gnome-extensions module must run before this script" >&2
    exit 1
fi
echo "  User Themes is $UUID"

# ------------------------------------------------------------- the base list
#
# The list is merged, never replaced: dash-to-dock, appindicator and the rest
# come from the base image and this file is named to be merged last, so
# whatever we write wins for accounts with no value of their own.
#
# Reading it is the part that needs care. The base does not put
# enabled-extensions in a dconf keyfile, it sets it as a compiled gschema
# default, so scanning the keyfiles alone finds nothing. That is exactly what
# happened: the script fell through to an empty base list and wrote a bare
# ['user-theme@...'], which turns the base image's extensions off for everyone.
#
# Ask gsettings first, inside a throwaway session bus, because that returns the
# effective value whatever sets it. Only if that is unavailable fall back to
# walking the keyfiles.
current=$(dbus-run-session -- gsettings get org.gnome.shell enabled-extensions 2>/dev/null || true)
source_note="gsettings"

if [[ -z $current || $current == "@as []" || $current == "'@as []'" ]]; then
    source_note="dconf keyfiles"
    current=""
    while read -r f; do
        [[ -n $f ]] || continue
        current=$(sed -nE "s/^\s*enabled-extensions\s*=\s*(.*)$/\1/p" "$f" | tail -1)
    done < <(
        for dir in "$DBDIR"/*.d; do
            [[ -d $dir ]] || continue
            for f in "$dir"/*; do
                [[ -f $f ]] && grep -qE '^\s*enabled-extensions\s*=' "$f" 2>/dev/null && printf '%s\n' "$f"
            done
        done
    )
fi

if [[ -z $current || $current == "@as []" || $current == "'@as []'" ]]; then
    echo "error: could not read the base enabled-extensions list from gsettings or $DBDIR" >&2
    echo "       refusing to write a bare ['$UUID'], which would disable every" >&2
    echo "       extension the base image ships" >&2
    exit 1
fi
echo "  base list ($source_note): $current"

merged=$(python3 - "$UUID" "$current" <<'PY'
import re
import sys

uuid, raw = sys.argv[1], sys.argv[2].strip()
if not (raw.startswith("[") and raw.endswith("]")):
    sys.exit("cannot parse enabled-extensions: %r" % raw)

entries = re.findall(r"'((?:[^'\\]|\\.)*)'", raw)
if not entries:
    sys.exit("no entries parsed out of enabled-extensions: %r" % raw)

for e in entries:
    if e.replace("\\'", "'") == uuid:
        print(raw)
        raise SystemExit

print("[" + ", ".join("'%s'" % e for e in entries + [uuid]) + "]")
PY
)

if [[ $merged == "$current" ]]; then
    echo "  $UUID already in the system list"
else
    mkdir -p "$(dirname "$TARGET")"
    {
        echo "# Generated by enable-user-theme-systemwide.sh, merged from the base image list."
        echo "[org/gnome/shell]"
        echo "enabled-extensions=$merged"
    } >"$TARGET"
    echo "  wrote $TARGET"
    echo "    enabled-extensions=$merged"
fi

# The merge only counts if nothing from the base got dropped on the way.
for keep in $(python3 -c "
import re,sys
raw=sys.argv[1]
print(' '.join(re.findall(r\"'((?:[^'\\\\]|\\\\.)*)'\", raw)))" "$current"); do
    if [[ $keep == "$UUID" ]]; then continue; fi
    if [[ $merged != *"$keep"* ]]; then
        echo "error: $keep was in the base list but is missing from the merged list" >&2
        exit 1
    fi
done
echo "  every extension from the base survived the merge"

if command -v dconf >/dev/null 2>&1; then
    dconf update
    if dconf dump /org/gnome/shell/ 2>/dev/null | grep -q "$UUID"; then
        echo "  compiled: $UUID is in the system extension list"
    else
        echo "error: $UUID is not in the compiled dconf database" >&2
        exit 1
    fi
else
    echo "  dconf not installed, left the database uncompiled"
fi
